apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: dev-policy-dependency-cm-1
spec:
  remediationAction: inform 
  object-templates:
  - complianceType: musthave
    RemediationAction: enforce
    objectDefinition:
      apiVersion: v1
      data:
        a: "1"
      kind: ConfigMap
      metadata:
        name: data1
        namespace: rhacs-operator
