apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: oauth-config
policyDefaults:
  remediationAction: enforce
  namespace: acm-config
  placement:
   placementRulePath: placementrule.yaml 
policies:
  - name: dev-oauth-config
    manifests:
      - path: manifests
