apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app3
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-apps/app3-manifest 
    repoURL: https://github.com/anraman1/acm_config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    
