apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anraman1/acm_config.git
    targetRevision: main
    path: argo-apps
  destination:
    name: cluster2
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


      provider "aws" {
  region = "us-east-1"
}


resource "aws_key_pair" "argocd_key" {
  key_name   = "argocd-lab-key"
  public_key = file("~/.ssh/id_rsa.pub")
}


resource "aws_security_group" "argocd_lab_sg" {
  name = "argocd-lab-sg"

  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    from_port   = 30080
    to_port     = 30080
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

data "aws_ami" "ubuntu" {
  most_recent = true
  owners      = ["099720109477"] # Canonical Ubuntu

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
  }
}

resource "aws_instance" "argocd_lab" {
  ami                    = data.aws_ami.ubuntu.id
  instance_type          = "t3.medium"
  key_name               = aws_key_pair.argocd_key.key_name
  vpc_security_group_ids = [aws_security_group.argocd_lab_sg.id]

  user_data = <<-EOF
#!/bin/bash
set -e

apt-get update -y
apt-get install -y curl

curl -sfL https://get.k3s.io | sh -

export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

kubectl create namespace argocd

kubectl apply -n argocd --server-side --force-conflicts \
  -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

kubectl -n argocd patch svc argocd-server \
  -p '{"spec": {"type": "NodePort", "ports": [{"name": "https", "port": 443, "targetPort": 8080, "nodePort": 30080}]}}'

kubectl -n argocd wait --for=condition=Available deployment/argocd-server --timeout=300s

kubectl -n argocd get secret argocd-initial-admin-secret \
  -o jsonpath="{.data.password}" | base64 -d > /home/ubuntu/argocd-password.txt

chown ubuntu:ubuntu /home/ubuntu/argocd-password.txt
EOF

  tags = {
    Name = "argocd-lab"
  }
}

output "argocd_url" {
  value = "https://${aws_instance.argocd_lab.public_ip}:30080"
}

output "ssh_command" {
  value = "ssh -i argocd-lab.pem ubuntu@${aws_instance.argocd_lab.public_ip}"
}

## AWS access KEY ID and SECRET Id
variable "aws_access_key_id" {
  description = "AWS Access Key ID"
  type        = string
}   
variable "aws_secret_access_key" {
  description = "AWS Secret Access Key"
  type        = string
  sensitive   = true
}   


#assing values to the variables

variable "aws_region" {
  description = "AWS Region"
  type        =  string
  default     = "us-east-1" 
}

output "aws_access_key_id" {
  value = var.aws_access_key_id
}


resource "aws_instance" "k3s_cluster_2" {
  ami                    = data.aws_ami.ubuntu.id
  instance_type          = "t3.medium"
  vpc_security_group_ids = [aws_security_group.argocd_lab_sg.id]
  key_name               = aws_key_pair.argocd_key.key_name

  user_data = <<-EOF
    #!/bin/bash
    curl -sfL https://get.k3s.io | sh -
    mkdir -p /home/ubuntu/.kube
    cp /etc/rancher/k3s/k3s.yaml /home/ubuntu/.kube/config
    chown -R ubuntu:ubuntu /home/ubuntu/.kube
  EOF

  tags = {
    Name = "k3s-standalone-cluster-2"
  }
}

output "k3s_cluster_2_public_ip" {
  value = aws_instance.k3s_cluster_2.public_ip
}


output "k3s_argolab-public_ip" {
  value = aws_instance.argocd_lab.public_ip


}



#####

repo/
└── apps/
    └── payment-cluster2.yaml


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-cluster2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anraman1/acm_config.git
    targetRevision: main
    path: acs-operator
  destination:
    name: cluster2
    namespace: payment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
