apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://172.31.0.166:6443
  project: default
  source:
    path: argo-apps
    repoURL: https://github.com/anraman1/acm_config.git
    targetRevision: main
