apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-dev-clusterrolebinding 
  namespace: acm-config
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - key: environment 
            operator: In
            values:
              - dev
