resources:
- ../../base

patches:
 - target:
    kind: ClusterRoleBinding
   patch: |-
    - op: replace 
      path: /subjects/0
      value:  
        apiGroup: rbac.authorization.k8s.io
        kind: User
        name: ecslab
