apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: openshift-pipelines-operator-rh.v1.15.3
  namespace: openshift-pipeline
status:
  phase: "Succeeded"


apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: dev-rh-openshift-pipeline-status
spec:
  object-templates:
  - complianceType: musthave
    remediationAction: enforce
    objectDefinition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      metadata:
        name: openshift-pipelines-operator-rh.v1.15.3
        namespace: openshift-pipeline
      status:
        phase: Succeeded
## create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-pipeline
  