apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: dev-redis-operator 
policyDefaults:
  consolidateManifests: false
  remediationAction: enforce
  namespaceSelector: 
     matchExpressions:
            - key: apps 
              operator: In
              values:
              - redis-operator 
     include:
              - redis-*
  namespace: acm-config
  placement:
   placementPath: placement.yaml 
policies:
  - name: dev-redis-operator
    manifests:
      - path: manifests/redis-operator.yaml
