apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: config-data-policies
policyDefaults:
  namespace: acm-config
  placement:
   placementRulePath: placementrule.yaml 
policies:
  - name: dev-rh-openshift-pipeline
    manifests:
      - path: manifests
