apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-machine-config
  namespace: acm-config 
spec:
  clusterSelector:
    matchExpressions:
      - key: environment 
        operator: In
        values:
          - dev 
